### ISSUE TITLE
[Image Component] [Rise Storage] Content that has transparency in Rise Storage

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1170]
**Defect:** when there’s content in Rise Storage that has transparency, the transparent background should have a color value of #f2f2f2 or #999999, not a checkerboard pattern.

![image28_jpg__751×355_](https://user-images.githubusercontent.com/1440943/62787985-8ec4e680-ba8b-11e9-8fed-fab91375851f.png)

**Comment by willread** [comment]
@jasoncaldwell This has been fixed in [this PR](https://github.com/Rise-Vision/rise-vision-apps/pull/1192). Please validate and let me know when I can close this.

**Comment by jasoncaldwell** [comment]
@willread The background color in Rise Storage looks good:

![Rise_Vision___Apps](https://user-images.githubusercontent.com/1440943/63381870-30d3b100-c35f-11e9-96b2-7cce69ac4882.png)

But I'm still seeing a checkerboard pattern in the Image Component itself:

![Rise_Vision___Apps](https://user-images.githubusercontent.com/1440943/63381938-4e087f80-c35f-11e9-949c-566d3b34ec81.png)

**Comment by jasoncaldwell** [comment]
@willread Copy that. Thanks!

**Comment by jasoncaldwell** [comment]
@willread Also, I opened a new issue for the big, transparent PNG not showing in preview:

https://github.com/Rise-Vision/rise-vision-apps/issues/1230

Thanks!

**Comment by willread** [comment]
@jasoncaldwell I've pushed a fix for this, please validate as soon as you have a chance.

**Comment by jasoncaldwell** [comment]
@willread Thanks! What staging server should I be viewing this on?

**Comment by willread** [comment]
@jasoncaldwell It's viewable on the main apps server.

**Comment by jasoncaldwell** [comment]
@willread Looks good! You can close.
